VisitorManagement/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NETCore.MailKit.Core;
using System.Dynamic;
using System.Net;
using System.Net.Mail;
using VisitorManagement.Data;
using VisitorManagement.Models;
using VisitorManagement.Service;

namespace VisitorManagement.Controllers
{
    public class DashboardController : Controller
    {
        AppDBContext context;
        private readonly SignInManager<Admin> signInManager;
        private readonly IEmailService _EmailService;
        public DashboardController(AppDBContext context, SignInManager<Admin> signInManager, IEmailService emailService)
        {
            this.context = context;
            this.signInManager = signInManager;
            _EmailService = emailService;
        }

        public IActionResult Index()
        {
            DashboardViewModel model = new();
            model.EmployeeCheckIn = context.EmployeeRegister.Where(x => x.Last_login.Value.Date == DateTime.Now.Date).Count();
            model.EmployeeCheckout = context.EmployeeRegister.Where(x => x.Last_logout.Value.Date == DateTime.Now.Date).Count();

            model.VisitorCheckIn = context.VisitorRegister.Where(x => x.Last_login.Value.Date == DateTime.Now.Date).Count();
            model.VisitorCheckOut = context.VisitorRegister.Where(x => x.Last_logout.Value.Date == DateTime.Now.Date).Count();
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Logout()
        {
            await signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

VisitorManagement/Controllers/DeliveryController.cs
using Microsoft.AspNetCore.Mvc;
using VisitorManagement.Data;
using VisitorManagement.Models;

namespace VisitorManagement.Controllers
{
    public class DeliveryController : Controller
    {
        private AppDBContext context;

        public DeliveryController(AppDBContext context)
        {
            this.context = context;
        }

        public IActionResult Index()
        {
            var data = context.Delivery.ToList();
            return View(data);
        }
        public IActionResult CheckIn()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CheckIn(Delivery delivery)
        {
            context.Delivery.Add(delivery);
            return View();
        }

    }
}

VisitorManagement/Controllers/EmployeesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using VisitorManagement.Data;
using VisitorManagement.Models;
using VisitorManagement.Service;
using System.Linq;

namespace VisitorManagement.Controllers
{
    public class EmployeesController : Controller
    {
        AppDBContext context;

        public EmployeesController(AppDBContext context)
        {
            this.context = context;
        }
        public IActionResult Index()
        {
            var employees = context.Employee.ToList();
            return View(employees);
        }
        public IActionResult Details(int persal)
        {
            var reg = context.EmployeeRegister.Where(x => x.EmployeeId == persal).ToList();
            var emp = context.Employee.Find(persal);
            emp.Persal = persal;
            EmployeeProfileViewModel employeeProfileViewModel = new EmployeeProfileViewModel()
            {
                Employee = emp,
                EmployeeRegister = reg
            };
            return View(employeeProfileViewModel);
        }
        [HttpPost]
        public IActionResult Details(EmployeeProfileViewModel viewModel)
        {
            var reg = context.EmployeeRegister.Where(x => x.EmployeeId == viewModel.Employee.Persal).ToList();

            var emp = viewModel.Employee;
            context.Entry(emp).State = Microsoft.EntityFrameworkCore.EntityState.Modified;

            context.SaveChanges();
            viewModel.EmployeeRegister = reg;
            TempData["success"] = "Successfully updated";

            return View(viewModel);
        }
        public IActionResult CheckIn()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Employee employee)
        {
            if (employee != null)
            {
                var emp = context.Employee.Find(employee.Persal);
                if (emp == null)
                {
                    employee.Status = "signed out";
                    context.Employee.Add(employee);
                    context.SaveChanges();
                    TempData["success"] = "Employee profile has been successfully created";
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["error"] = "Percal Number already registred";
                    ModelState.AddModelError("", "Persal already registered");
                }
            }
            return View();
        }
        public IActionResult EmployeeChecksIn(EmployeeCheckInViewModel viewModel)
        {
            var names = HttpContext.Session.GetString("Names");
            ViewBag.e_name = names;
            ViewBag.Temp = viewModel.Temperature;

            HttpContext.Session.SetInt32("EmployeeId", viewModel.Percal);
            
            HttpContext.Session.SetString("Temp", viewModel.Temperature.ToString().Trim());
            if (viewModel.AssetType !=null && viewModel.AssetType !=null) 
            {
                HttpContext.Session.SetString("Asset_num", viewModel.AssetNumber);
                HttpContext.Session.SetString("Asset_type", viewModel.AssetType);
            }
            EmployeeRegister employee_reg = new()
            {
                EmployeeId = viewModel.Percal,
                Temp = viewModel.Temperature,
                Asset_num = viewModel.AssetNumber,
                Asset_type = viewModel.AssetType,

            };
             

            return View(employee_reg);
        }
        [HttpPost]
        public IActionResult EmployeeChecksIn(EmployeeRegister model, IFormCollection form)
        {
            var d_t = DateTime.Now;
            var emp = context.Employee.Find(model.EmployeeId);
            if(emp != null)
            {
                emp.LastCheckIn = d_t;
                emp.Status = "signed in";
                context.Employee.Update(emp);
            }
            model.Last_login = d_t;
            context.EmployeeRegister.Add(model);
            context.SaveChanges();
            TempData["success"] = "Successfully logged in";
            //var EMP_REG = context.EmployeeRegister.Where(x => x.EmployeeId == viewModel.EmployeeId && x.Last_login.Value.Date == emp.LastCheckIn.Value.Date);
            
            //var data = new EmployeeRegister()
            //{
            //    Temp = double.Parse(HttpContext.Session.GetString("Temp")),
            //    Asset_num = HttpContext.Session.GetString("Asset_num"),
            //    EmployeeId = (int)HttpContext.Session.GetInt32("EmployeeId"),
            //    Asset_type = HttpContext.Session.GetString("Asset_type"),
            //    Last_login = d_t,
                
            //};

            //healthCheck.EmployeeId = data.EmployeeId;
            //context.EmployeeRegister.Add(data);
            //context.HealthCheck.Add(healthCheck);
            return View();
        }
        [HttpPost]
        public IActionResult CheckIn(EmployeeCheckInViewModel viewModel)
        {
            if (viewModel.Percal > 0)
            {
                var emp = context.Employee.Find(viewModel.Percal);

                if (emp != null)
                {
                    if (emp.Status == "signed out")//signed out
                    {
                        //if signed out
                        //check last signed in dates
                        if (emp.LastCheckIn.HasValue)
                        {
                            if ((DateTime.Now - emp.LastCheckIn.Value).TotalDays >= 7)
                            {
                                //create id session
                                //create temperature session
                                //asset name  session
                                //create asset number session
                               
                                HttpContext.Session.SetString("Names", $"{emp.FirstName} {emp.LastName}");
                                

                                return RedirectToAction("EmployeeChecksIn", viewModel);//with healthcheck
                            }
                            else
                            {
                                var d_t = DateTime.Now;
                                //var EMP_REG = context.EmployeeRegister.Where(x => x.EmployeeId == viewModel.EmployeeId && x.Last_login.Value.Date == emp.LastCheckIn.Value.Date);
                                emp.Status = "signed in";
                                emp.LastCheckIn = d_t;

                                //FIND LAST CHECKED IN FROM REGISTER
                                EmployeeRegister employeeRegister = new EmployeeRegister()
                                {
                                    Asset_num = viewModel.AssetNumber,
                                    EmployeeId = viewModel.Percal,
                                    Temp = viewModel.Temperature,
                                    Last_login = d_t,
                                    HealthCheck = null
                                };
                                context.Employee.Update(emp);
                                context.EmployeeRegister.Add(employeeRegister);
                                context.SaveChanges();
                                TempData["success"] = "Employee successfully checked in";
                                return RedirectToAction("CheckIn");
                            }
                        }
                        else
                        {
                            HttpContext.Session.SetString("Names", $"{emp.FirstName} {emp.LastName}");
                            return RedirectToAction("EmployeeChecksIn", viewModel);
                        }
                    }
                    else
                    {
                        TempData["error"] = "Employee is currently signed in from last session";
                        if (emp.LastCheckIn.HasValue)
                        {
                            ModelState.AddModelError("", $"Employee is currently signed it, from {emp.LastCheckIn.Value:dddd, dd/MM/yyyy}");
                        }
                    }


                    //var emp_reg = context.EmployeeRegister.First(x => (x.Last_login.Value - DateTimeOffset.Now).TotalDays <= 7);
                    //if (emp_reg == null)
                    //{
                    //    return RedirectToAction("EmployeeChecKsIn", viewModel);
                    //}
                    //else
                    //{

                    //}
                }
                else
                {
                    TempData["error"] = "Persal not registered";
                }
            }
            else
            {
                TempData["error"] = "Persal not registered";
            }
            return View(viewModel);
        }

        public IActionResult CheckOut()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CheckOut(Employee employee)
        {
            if (ModelState.IsValid)
            {
                var emp = context.Employee.Find(employee.Persal);
                if(emp != null)
                {
                    var dt = DateTime.Now;
                    var emp_reg = context.EmployeeRegister.Single(x => x.EmployeeId == emp.Persal && x.Last_login == emp.LastCheckIn);
                    emp.LastCheckOut = dt;
                    emp_reg.Last_logout = dt;
                    emp.Status = "signed out";
                    context.Employee.Update(emp);
                    context.SaveChanges();
                    ModelState.Clear();
                    TempData["success"] = "Successfully Logged out";
                }
            }
            return View(employee);
        }
        public IActionResult Acknowladge()
        {
            return View();
        }

    }
}

VisitorManagement/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;

namespace VisitorManagement.Controllers
{
    public class SettingsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

VisitorManagement/Views/Shared/_Layout.cshtml
@inject SignInManager<Admin> identityUser;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>VISITOR MANAGEMENT</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/831d91fe92.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/adminlte.min.css">
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="/plugins/fontawesome-free/css/all.min.css">
    <!-- overlayScrollbars -->
    <link rel="stylesheet" href="/plugins/overlayScrollbars/css/OverlayScrollbars.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="/dist/css/adminlte.min.css">

    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />


</head>
<body class="hold-transition light-mode sidebar-mini layout-fixed layout-navbar-fixed layout-footer-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-dark">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <form method="post" asp-action="Logout" asp-controller="Dashboard">
                        <input class="btn-sm btn-info" type="submit" value="Logout" />
                    </form>
                </li>
            </ul>

            <!-- Right navbar links -->

        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
           >
            <!-- Brand Logo -->
            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel pb-3 mb-3 d-flex">
                  
                    <div class="info">
                        <a href="#" class="d-block">@User.Identity.Name</a>
                    </div>
                </div>

                <!-- SidebarSearch Form -->
                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        
                         <li class="nav-item">
                            <a asp-area="" asp-controller="Dashboard" asp-action="Index" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Dashboard
                                    <span class="right badge badge-danger"></span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Visitors" asp-action="Index" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Visitors
                                    <span class="right badge badge-danger"></span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Employees" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Employees
                                    <span class="right badge badge-danger"></span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Delivery" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Delivery
                                    <span class="right badge badge-danger"></span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Temperature" asp-action="Index" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Temperature
                                    <span class="right badge badge-danger"></span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Admin" asp-action="Index" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Admin
                                    <span class="right badge badge-danger"></span>
                                </p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Settings" asp-action="Index" class="nav-link">
                                <i class="nav-icon fas fa-th"></i>
                                <p>
                                    Settings
                                    <span class="right badge badge-danger"></span>
                                </p>
                            </a>
                        </li>

                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="d-inline justify-content-center">
                            <img src="/img/t.png" style=" height:50px"/>
                            <h5 class="m-0">VISITOR MANAGEMENT</h5>
                        </div><!-- /.col -->

                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    <!-- Info boxes -->
                    <div class="row">
                        <div class="col-12">
                            <!-- Default box -->
                            <div class="card">
                                <div class="card-body">
                                    @RenderBody()
                                </div>
                                <!-- /.card-body -->
                                <!-- /.card-footer-->
                            </div>
                            <!-- /.card -->
                        </div>
                    </div>

                </div><!--/. container-fluid -->
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        <footer class="main-footer">
            <strong>Copyright &copy; 2014-2021 <a>LEGAL &amp; DEBT MANAGEMENT</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 1.0.0
            </div>
        </footer>
    </div>
    <script src="/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- overlayScrollbars -->
    <script src="/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
    <!-- AdminLTE App -->
    <script src="/dist/js/adminlte.js"></script>

    <!-- PAGE PLUGINS -->
    <!-- jQuery Mapael -->
    <script src="/plugins/jquery-mousewheel/jquery.mousewheel.js"></script>
    <script src="/plugins/raphael/raphael.min.js"></script>
    <script src="/plugins/jquery-mapael/jquery.mapael.min.js"></script>
    <script src="/plugins/jquery-mapael/maps/usa_states.min.js"></script>
    <!-- ChartJS -->
    <script src="/plugins/chart.js/Chart.min.js"></script>

    <!-- AdminLTE for demo purposes -->
    <script src="/dist/js/demo.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="/dist/js/pages/dashboard2.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @section Scripts {
    @{await Html.RenderPartialAsync("_Notification");}
}

</body>
</html>

VisitorManagement/Views/Shared/_LeftMenu.cshtml
<ul class="list-group">
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
    </li>
    <li class="nav-item">
        <a class="nav-link text-dark" asp-area="" asp-controller="NextController" asp-action="Index">another menu link</a>
    </li>
</ul>

VisitorManagement/Views/Shared/_Login.cshtml
@inject SignInManager<Admin> identityUser;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VisitorManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/VisitorManagement.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        
    </header>


    <div class="main">
        <main role="main" class="pb-3">
            @RenderBody()
            
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

VisitorManagement/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
	</script>
}
@if(TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
     <script type="text/javascript">
        toastr.error('@TempData["error"]');
	</script>
}